language: python
python:
    - "2.6"
    - "2.7"
# command to install dependencies
install:
    - pip install .
# before
before_script:
    - cp travis_ci/manage.py manage.py
    - python manage.py syncdb --noinput
    - python manage.py migrate
# command to run tests
script:
    - python manage.py test spotseeker_server
